### ISSUE TITLE
Your Travis config is hitting our IRC channel

### ISSUE THREAD

**Issue by ComicIronic** [mattroks101/bunkerstation#21]
Hey man, we appreciate that you liked our code enough to use it as a basis for your own codebase, but you've managed to take a few config files that aren't really meant to be shared between codebases.

One of these is part of the `.travis.yml` that sends notifications to our IRC when a build runs.

**Comment by Nienhaus** [comment]
AHAHAHAH

**Comment by Zuhayr** [comment]
:bee:

**Comment by ErinCrowe** [comment]
Thanks for letting us know.

**Comment by mattroks101** [comment]
Super sorry about that. When putting this up I fucked around with the config and then didn't actually check it over. That's my bad. This'll get rectified ASAP.

**Comment by Zuhayr** [comment]
#22
