### ISSUE TITLE
Some new interaction bugs

### ISSUE THREAD

**Issue by mattroks101** [mattroks101/bunkerstation#34]
- [x] You can't fuck women even if they're naked. 
- [x] You can fuck fully clothed.
- [x] You can fuck yourself.
- [x] Can't initiate the gay sex.

@Zuhayr plz fix

**Comment by Zuhayr** [comment]
:8ball:

**Comment by mattroks101** [comment]
So for two of these I did runtime my own dick off. The others still stand.

**Comment by Zuhayr** [comment]
#35
